### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by uhlhosting** [yiwkr/mattermost-plugin-janken#1]
Hi,

Would love the chance to have this in english also. Any way one could get involved to help with translations, it cannot have so many lines visible to users. Keep up the good work! Domo Arigato Gozaimasu

**Comment by yiwkr** [comment]
Thank you for your comment. I will try to translate the text of this plugin by myself, so please check it when I finish translating.

**Comment by yiwkr** [comment]
@uhlhosting I translated Japanese text into English and added "-l" option to select language. (The default language is English.)

```
Usage: /janken [-l en|ja]

Optional arguments
  -l en|ja   Language (default: en)
```

To use the new plugin, please download [com.github.yiwkr.mattermost-plugin-janken_0.0.1.tar.gz](https://github.com/yiwkr/mattermost-plugin-janken/files/3212271/com.github.yiwkr.mattermost-plugin-janken_0.0.1.tar.gz) and upload it to your mattermost server, or build and deploy from [topic/#1_translation](https://github.com/yiwkr/mattermost-plugin-janken/tree/topic/%231_translation) branch.

The translated text is [here](https://github.com/yiwkr/mattermost-plugin-janken/blob/topic/%231_translation/assets/active.en.toml). It would be appreciated if you could review my translation.

**Comment by uhlhosting** [comment]
Works great!, Thank you, I might help translating it if would be requests in ro, cz and de.

**Comment by yiwkr** [comment]
@uhlhosting Tanks for your proposal! If you translate it into other languages, please create new issues and PR's per language and translate it.

For your reference:

The following procedures are adopted from [goi18n documents](https://github.com/nicksnyder/go-i18n#command-goi18n-) for this plugin.

### Add new language

1. Create an empty message file for the language that you want to add (e.g. translate.ro.toml).

    ```
    touch assets/translate.ro.toml
    ```

2. Run the following command to populate translate.ro.toml with the messages to be translated.

    ```
    goi18n merge -outdir assets assets/active.en.toml assets/translate.ro.toml
    ```

3. After translate.ro.toml has been translated, rename it to active.ro.toml.

    ```
    mv assets/translate.ro.toml assets/active.ro.toml
    ````

### Translating new messages

1. Run `goi18n extract -outdir assets/ server/janken/` to update active.en.toml with the new messages.
2. Run `goi18n merge -outdir assets/ assets/active.\*.toml` to generate updated translate.\*.toml files.
3. Translate all the messages in the translate.\*.toml files.
4. Run `goi18n merge -outdir assets/ assets/active.*.toml assets/translate.*.toml` to merge the translated messages into the active message files.
